load('ext://helm_resource', 'helm_resource', 'helm_repo')
load('ext://namespace', 'namespace_create')

NAMESPACE = 'database'

def setup_postgres():
    namespace_create(NAMESPACE, allow_duplicates=True)

    helm_repo(
        'bitnami-repo', 
        'https://charts.bitnami.com/bitnami',
        labels=["HelmRepos"]
    )

    helm_resource(
        'postgres', 
        'bitnami/postgresql', 
        namespace = NAMESPACE, 
        flags=['--values=tilt_lib/postgres/values.local.yaml'],
        labels=["Database"]
    )
