// Code generated . DO NOT EDIT.
// ################################## DO NOT EDIT THIS FILE ######################################
// Common Sense Coding (https://github.com/cscoding21/csgen)

// Generate Date: 2024-07-30 11:30:49.873633915 -0700 PDT m=+0.005135357
// Implementation Name: csmig
// Developer Note: The contents of this file will be recreated each time its generator is called

// -----------------------------------------------------------------------------------------------

package migrations

import (
	"fmt"
	"testing"

	"github.com/cscoding21/csmig/shared"
)

func TestApply(t *testing.T) {
	config := shared.GetTestConfig()

	err := Apply(config)
	if err != nil {
		t.Error(err)
	}
}

func TestRollback(t *testing.T) {
	config := shared.GetTestConfig()

	err := Rollback(config)
	if err != nil {
		t.Error(err)
	}
}

func TestFindApplyMigrations(t *testing.T) {
	config := shared.GetTestConfig()

	appliedMigrations, err := FindAppliedMigrations(config)
	if err != nil {
		t.Error(err)
	}

	for _, am := range appliedMigrations {
		fmt.Println(am.Name, am.AppliedOn)
	}
}

func TestFindUnapplyMigrations(t *testing.T) {
	config := shared.GetTestConfig()

	unappliedMigrations, err := FindUnappliedMigrations(config)
	if err != nil {
		t.Error(err)
	}

	if len(unappliedMigrations) == 0 {
		fmt.Println("No unapplied migrations were found")
	}

	for _, um := range unappliedMigrations {
		fmt.Println(um.Name, um.FilePath)
	}
}
