# -*- mode: Python -*-

load('ext://namespace', 'namespace_create')
load('ext://helm_resource', 'helm_resource')

NAMESPACE = 'app'

def setup_csserver():
    namespace_create(NAMESPACE)

    docker_build(
        'csserver', 
        './csserver', 
        dockerfile = 'csserver/Dockerfile'
    )

    k8s_yaml(
        helm(
            './deploy/helm/csserver',
            name = 'csserver',
            namespace = NAMESPACE
        ),
    )