// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package idl

type List struct {
	ID     string      `json:"id"`
	Name   string      `json:"name"`
	Values []*ListItem `json:"values"`
}

type ListItem struct {
	Value string `json:"value"`
	Name  string `json:"name"`
}

type ListResults struct {
	Results []*List `json:"results,omitempty"`
}

type Query struct {
}
