load('ext://helm_resource', 'helm_resource', 'helm_repo')
load('ext://namespace', 'namespace_create')

NAMESPACE = 'ollama'

# https://github.com/otwld/ollama-helm

def setup_ollama():
    namespace_create(NAMESPACE, allow_duplicates=True)

    helm_repo(
        'ollama-helm-repo', 
        'https://otwld.github.io/ollama-helm/',
        labels=["HelmRepos"]
    )

    helm_resource(
        'ollama', 
        'ollama-helm/ollama', 
        namespace = NAMESPACE, 
        flags=['--values=tilt_lib/ollama/values.local.yaml', '--version=1.6.0'],
        labels=["Ollama"]
    )