// Code generated . DO NOT EDIT.
// ################################## DO NOT EDIT THIS FILE ######################################
// Common Sense Coding (https://github.com/cscoding21/csgen)

// Generate Date: 2024-09-15 19:02:24.232941334 -0700 PDT m=+0.289831130
// Implementation Name: csplanner
// Developer Note: The contents of this file will be recreated each time its generator is called

// -----------------------------------------------------------------------------------------------

package list

import (
	"context"
	"csserver/internal/common"
	"csserver/internal/config"
	"csserver/internal/interfaces"
	"csserver/internal/marshal"
	"csserver/internal/providers/nats"
	"csserver/internal/providers/surreal"
	"fmt"

	"github.com/cscoding21/csmap/utils"
	"github.com/opentracing/opentracing-go/log"
)

// ---This is the name of the object in the database
const ListIdentifier = "list"

// ListService is a service for interacting with lists.
type ListService struct {
	DBClient      surreal.DBClient
	ContextHelper interfaces.ContextHelpers
	PubSub        nats.PubSubProvider
}

// NewListService creates a new List service.
func NewListService(
	db surreal.DBClient,
	ch config.ContextHelper,
	ps nats.PubSubProvider) *ListService {

	return &ListService{
		DBClient:      db,
		ContextHelper: &ch,
		PubSub:        ps,
	}
}

// GetListByID gets a List by its ID.
func (s *ListService) GetListByID(ctx context.Context, id string) (*List, error) {
	outData, err := s.DBClient.GetObjectById(id)
	if err != nil {
		return common.HandleReturnWithValue[List](nil, err)
	}

	output, err := marshal.SurrealUnmarshal[List](outData)

	return common.HandleReturnWithValue(
		output,
		err,
	)
}

// FindAllLists return all List in the system
func (s *ListService) FindAllLists(ctx context.Context) (common.PagedResults[List], error) {
	pagingResults := common.NewPagedResultsForAllRecords[List]()
	sql := "select * from list where deleted_at is null order by name"

	results, resultCount, err := s.DBClient.FindPagedObjects(sql, pagingResults.Pagination, pagingResults.Filters)
	if err != nil {
		return pagingResults, err
	}

	pagingResults.Pagination.TotalResults = &resultCount
	unpacked, err := marshal.SurrealSmartUnmarshal[[]List](results)
	if err != nil {
		return pagingResults, err
	}

	pagingResults.Results = common.RefToVal(unpacked)
	return pagingResults, nil
}

// FindList return a paged list of List based on filter criteria
func (s *ListService) FindLists(ctx context.Context, paging common.Pagination, filters common.Filters) (common.PagedResults[List], error) {
	out := common.NewPagedResults[List](paging, filters)

	whereSql, _ := s.DBClient.BuildWhereClauseFromFilters(&filters)

	sql := fmt.Sprintf("SELECT * FROM list WHERE true AND deleted_at is null %s ORDER BY name", whereSql)

	rawResults, count, err := s.DBClient.FindPagedObjects(sql, paging, filters)
	if err != nil {
		log.Error(err)
		return out, err
	}

	out.Pagination.TotalResults = &count
	unpacked, err := marshal.SurrealSmartUnmarshal[[]List](rawResults)
	if err != nil {
		return out, err
	}

	out.Results = common.RefToVal(unpacked)
	return out, nil
}

// CreateList creates a new List.
func (s *ListService) CreateList(ctx context.Context, input *List) (common.UpdateResult[List], error) {

	val := input.Validate()
	if !val.Pass {
		return common.NewUpdateResult[List](&val, input), fmt.Errorf("validation failed")
	}

	userEmail := s.ContextHelper.GetUserEmailFromContext(ctx)

	outData, err := s.DBClient.CreateObject(userEmail, ListIdentifier, input)
	if err != nil {
		return common.NewUpdateResult[List](&val, input), err
	}

	outArray, err := marshal.SurrealUnmarshal[[]List](outData)
	if err != nil {
		return common.NewUpdateResult[List](&val, input), err
	}

	outObj := utils.RefToVal(outArray)[0]
	return common.NewUpdateResult[List](&val, &outObj), nil
}

// UpdateList update an existing List.
func (s *ListService) UpdateList(ctx context.Context, input *List) (common.UpdateResult[List], error) {

	val := input.Validate()
	if !val.Pass {
		return common.NewUpdateResult[List](&val, input), fmt.Errorf("validation failed")
	}

	userEmail := s.ContextHelper.GetUserEmailFromContext(ctx)

	lastObj, err := s.GetListByID(ctx, input.ID)
	if err != nil {
		return common.NewUpdateResult[List](&val, input), err
	}

	//---ensure the integrity of the creation data
	input.CreatedAt = lastObj.CreatedAt
	input.CreatedBy = lastObj.CreatedBy

	outData, err := s.DBClient.UpdateObject(userEmail, input.ID, input)
	if err != nil {
		return common.NewUpdateResult[List](&val, input), err
	}

	outObj, err := marshal.SurrealUnmarshal[List](outData)
	if err != nil {
		return common.NewUpdateResult[List](&val, input), err
	}

	return common.NewUpdateResult[List](&val, outObj), nil
}

// DeleteList deletes a List.
func (s *ListService) DeleteList(ctx context.Context, id string) error {
	userEmail := s.ContextHelper.GetUserEmailFromContext(ctx)

	list, err := s.GetListByID(ctx, id)
	if err != nil {
		return common.HandleReturn(err)
	}

	return common.HandleReturn(
		s.DBClient.SoftDeleteObject(userEmail, list),
	)
}
