// Code generated . DO NOT EDIT.
// ################################## DO NOT EDIT THIS FILE ######################################
// Common Sense Coding (https://github.com/cscoding21/csgen)

// Generate Date: 2024-06-25 12:51:26.246289879 -0700 PDT m=+0.048422487
// Implementation Name: csval

// -----------------------------------------------------------------------------------------------

package list

import "github.com/cscoding21/csval/validate"

// Validate checks the fields in the struct List to ensure it conforms to business rules
func (obj *List) Validate() validate.ValidationResult {
	result := validate.NewSuccessValidationResult()

	// ---Field: Name
	result.Append(validate.IsNotEmpty("Name", obj.Name))

	return result
}
