# -*- mode: Python -*-

load('ext://namespace', 'namespace_create')
load('ext://helm_resource', 'helm_resource')

NAMESPACE = 'app'

def setup_csprocessor():
    namespace_create(NAMESPACE, allow_duplicates=True)

    docker_build(
        'csprocessor', 
        './csserver', 
        dockerfile = 'csserver/DockerProcessor'
    )

    k8s_yaml(
        helm(
            './deploy/helm/csprocessor',
            name = 'csprocessor',
            namespace = NAMESPACE
        ),
    )