package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"csserver/internal/appserv/graph"
	"csserver/internal/appserv/graph/idl"
	"fmt"
)

// FindAllLists is the resolver for the findAllLists field.
func (r *queryResolver) FindAllLists(ctx context.Context) (*idl.ListResults, error) {
	panic(fmt.Errorf("not implemented: FindAllLists - findAllLists"))
}

// GetList is the resolver for the getList field.
func (r *queryResolver) GetList(ctx context.Context, nameOrID string) (*idl.List, error) {
	panic(fmt.Errorf("not implemented: GetList - getList"))
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
