package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"csserver/internal/appserv/graph"
	"csserver/internal/appserv/graph/idl"
	"fmt"
)

// CurrentTime is the resolver for the currentTime field.
func (r *subscriptionResolver) CurrentTime(ctx context.Context) (<-chan *idl.TimeResponse, error) {
	panic(fmt.Errorf("not implemented: CurrentTime - currentTime"))
}

// NotificationUpdate is the resolver for the notificationUpdate field.
func (r *subscriptionResolver) NotificationUpdate(ctx context.Context) (<-chan string, error) {
	panic(fmt.Errorf("not implemented: NotificationUpdate - notificationUpdate"))
}

// Subscription returns graph.SubscriptionResolver implementation.
func (r *Resolver) Subscription() graph.SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
