// Code generated . DO NOT EDIT.
// ################################## DO NOT EDIT THIS FILE ######################################
// Common Sense Coding (https://github.com/cscoding21/csgen)

// Generate Date: 2024-06-25 12:51:26.290051505 -0700 PDT m=+0.092184098
// Implementation Name: csplanner

// -----------------------------------------------------------------------------------------------

package user

import (
	"context"
	"csserver/internal/common"
	"csserver/internal/interfaces"
	"csserver/internal/marshal"
	"csserver/internal/providers/surreal"
)

// ---This is the name of the object in the database
const UserIdentifier = "user"

// UserService is a service for interacting with lists.
type UserService struct {
	DBClient      surreal.DBClient
	ContextHelper interfaces.ContextHelpers
}

// NewUserService creates a new User service.
func NewUserService(
	db surreal.DBClient) *UserService {

	return &UserService{
		DBClient: db,
	}
}

// GetUserByID gets a User by its ID.
func (s *UserService) GetUserByID(ctx context.Context, id string) (*User, error) {
	outData, err := s.DBClient.GetObjectById(id)
	if err != nil {
		return common.HandleReturnWithValue[User](nil, err)
	}

	output, err := marshal.SurrealUnmarshal[User](outData)

	return common.HandleReturnWithValue(
		output,
		err,
	)
}

// FindAllUser return all User in the system
func (s *UserService) FindAllUser(ctx context.Context) (common.PagedResults[User], error) {
	pagingResults := common.NewPagedResultsForAllRecords[User]()
	sql := "select * from user where deleted_at is null order by name"

	results, resultCount, err := s.DBClient.FindPagedObjects(sql, pagingResults.Pagination, pagingResults.Filters)
	if err != nil {
		return pagingResults, err
	}

	pagingResults.Pagination.TotalResults = &resultCount
	unpacked, err := marshal.SurrealSmartUnmarshal[[]User](results)
	if err != nil {
		return pagingResults, err
	}

	pagingResults.Results = common.RefToVal(unpacked)
	return pagingResults, nil
}

// UserList creates a new User.
func (s *UserService) CreateUser(ctx context.Context, input *User) (*User, error) {

	userID := s.ContextHelper.GetUserIDFromContext(ctx)

	outData, err := s.DBClient.CreateObject(userID, UserIdentifier, input)
	if err != nil {
		return common.HandleReturnWithValue[User](nil, err)
	}

	list, err := marshal.SurrealSmartUnmarshal[User](outData)

	return common.HandleReturnWithValue(list, err)
}

// UpdateUser update an existing User.
func (s *UserService) UpdateUser(ctx context.Context, input *User) (*User, error) {

	userID := s.ContextHelper.GetUserIDFromContext(ctx)

	outData, err := s.DBClient.UpdateObject(userID, input.ID, input)
	if err != nil {
		return common.HandleReturnWithValue[User](nil, err)
	}

	output, err := marshal.SurrealUnmarshal[User](outData)

	return common.HandleReturnWithValue(output, err)
}

// DeleteUser deletes a User.
func (s *UserService) DeleteUser(ctx context.Context, id string) error {
	userID := s.ContextHelper.GetUserIDFromContext(ctx)

	list, err := s.GetUserByID(ctx, id)
	if err != nil {
		return common.HandleReturn(err)
	}

	return common.HandleReturn(
		s.DBClient.SoftDeleteObject(userID, list),
	)
}
