services_dir: /home/jeph/projects/cscoding21/csplanner/csserver/internal/services

services:
  - name: Activity
    path: ""
  - name: Artifact
    path: ""
  - name: Comment
    path: ""
  - name: List
    path: ""
  - name: Notification
    path: ""
  # - name: Organization
  #   path: ""
  - name: Project
    path: ""
  - name: ProjectTemplate
    path: ""
  - name: Resource
    path: ""
  - name: Schedule
    path: ""
  - name: Appuser
    path: "iam"
  
  