# -*- mode: Python -*-

load('ext://namespace', 'namespace_create')
load('ext://helm_resource', 'helm_resource')

NAMESPACE = 'app'

def setup_csai():
    namespace_create(NAMESPACE, allow_duplicates=True)

    docker_build(
        'csai', 
        './csai', 
        dockerfile = 'csai/Dockerfile'
    )

    k8s_yaml(
        helm(
            './deploy/helm/csai',
            name = 'csai',
            namespace = NAMESPACE
        ),
    )