<script lang="ts">
	import { SectionSubHeading, UserCard } from "$lib/components";
	import type { Project, User } from "$lib/graphql/generated/sdk";
	import { formatCurrency, formatPercent, pluralize } from "$lib/utils/format";
	import { onMount } from "svelte";
	import TaskCard from "./TaskCard.svelte";
	import ProjectValueChart from "../ProjectValueChart.svelte";

    interface Props {
        project:Project
    }
    let { project }:Props = $props()

    let featurePriority = $state("high" as "high"|"med"|"low"|"notset")
    let valuePriority = $state("med" as "high"|"med"|"low"|"notset")
    let milestonePriority = $state("low" as "high"|"med"|"low"|"notset")

    const getFeaturePriority = ():"high"|"med"|"low"|"notset" => {
        if(!project) {
            console.log("feature unset")
            return "notset"
        }

        if(!project.projectFeatures || project.projectFeatures.length === 0) {
            console.log("feature high")
            return "high"
        }

        if(project.calculated?.featureStatusProposedCount && project.calculated?.featureStatusProposedCount > 0) {
            console.log("feature med")
            return "med"
        }

        console.log("feature low")
        return "low"
    }

    const getValuePriority = ():"high"|"med"|"low"|"notset" => {
        if(!project) {
            return "notset"
        }

        if(!project.projectValue || !project.projectValue.calculated?.netPresentValue || project.projectValue.calculated?.netPresentValue < 0.0) {
            return "high"
        }

        return "low"
    }

    const getMilestonePriority = ():"high"|"med"|"low"|"notset" => {
        if(!project) {
            return "notset"
        }

        if(project.calculated?.unhealthyTasks && project.calculated?.unhealthyTasks > 0) {
            return "high"
        }

        return "low"
    }

    onMount(() => {
        featurePriority = getFeaturePriority()
        valuePriority = getValuePriority()
        milestonePriority = getMilestonePriority()

        console.log("onmount", featurePriority)
    })
</script>


<div class="grid grid-cols-3 gap-16">
    <div>
        <SectionSubHeading>{project.projectBasics.name}</SectionSubHeading>

        <h3 class="text-gray-100 font-semibold">Owner</h3>
        <UserCard user={project.projectBasics.owner as User} />

        <h3 class="text-gray-100 font-semibold mt-6">Executive Summary</h3>
        <p class="py-2 text-gray-200">{@html project.projectBasics.description.replaceAll(/[\n]/g, "<br />")}</p>
    </div>

    <div class="col-span-2">
        <SectionSubHeading>TODO: Fill out the Details of this Project</SectionSubHeading>

        <TaskCard task="Break your project value down into a list of features" link="#features" priority={featurePriority}>
            This project currently has <b>{project.projectFeatures?.length}</b> {pluralize("feature", project.projectFeatures?.length as number)}

            <ul>
                <li>{project.calculated?.featureStatusAcceptedCount} accepted</li>
                <li>{project.calculated?.featureStatusRemovedCount} removed</li>
                <li>{project.calculated?.featureStatusProposedCount} proposed</li>
                <li>{project.calculated?.featureStatusDoneCount} done</li>
            </ul>
        </TaskCard>

        <TaskCard task="Estimate and characterize the value generated by this project" link="#value" priority={valuePriority}>
            <div class="flex">
                <div class="pr-4">
            This project has a 5-year NPV of 
            <b>{formatCurrency.format(project.projectValue.calculated?.netPresentValue as number)} </b>
            with an IRR of 
            <b>{formatPercent.format(project.projectValue.calculated?.internalRateOfReturn as number)}</b>
                    </div>
                    <div>
            <ProjectValueChart  {project} />
            </div>
            </div>
        </TaskCard>

        <TaskCard task="Create tasks and assign resources" link="#milestones" priority={milestonePriority}>
            This project currently has <b>{project.calculated?.totalTasks}</b> {pluralize("task", project.calculated?.totalTasks as number)}
            
            {#if project.calculated?.unhealthyTasks}
            <div class="text-yellow-400">
                Unhealthy tasks <b>{project.calculated?.unhealthyTasks}</b>
            </div>
            {:else}
            <div class="text-green-400">
                <b>{project.calculated?.healthyTasks}</b> tasks are healthy
            </div>
            {/if}
        </TaskCard>

    </div>
</div>
