<script lang="ts">
	import { SectionSubHeading, UserCard } from "$lib/components";
	import type { Project, User } from "$lib/graphql/generated/sdk";
	import { formatCurrency, formatPercent, pluralize } from "$lib/utils/format";
	import { onMount } from "svelte";
	import TaskCard from "./TaskCard.svelte";
	import ProjectValueChart from "../ProjectValueChart.svelte";
	import BasicsSummary from "./BasicsSummary.svelte";
	import { Button } from "flowbite-svelte";
	import { canEnterStatus, setProjectStatus } from "$lib/services/project";
	import { addToast } from "$lib/stores/toasts";
	import { reloadPage } from "$lib/utils/helpers";
	import UpdateStatusButtons from "./UpdateStatusButtons.svelte";

    interface Props {
        project:Project
    }
    let { project }:Props = $props()

    let featurePriority = $state("high" as "high"|"med"|"low"|"notset")
    let valuePriority = $state("med" as "high"|"med"|"low"|"notset")
    let milestonePriority = $state("low" as "high"|"med"|"low"|"notset")
    let showNextStatus = $derived(featurePriority === "low" && valuePriority === "low" && milestonePriority === "low")


    const setStatus = async (s:string) => {
		setProjectStatus(project.id as string, s).then((res) => {
			if (res.status?.success) {
				addToast({
					message: 'Project set to ' + s,
					dismissible: true,
					type: 'success'
				});

                reloadPage()
			} else {
				addToast({
					message: 'Error setting project status to ' + s + ': ' + res.status?.message,
					dismissible: true,
					type: 'error'
				});
			}
		});
	};

    const getFeaturePriority = ():"high"|"med"|"low"|"notset" => {
        if(!project) {
            console.log("feature unset")
            return "notset"
        }

        if(!project.projectFeatures || project.projectFeatures.length === 0) {
            console.log("feature high")
            return "high"
        }

        if(project.calculated?.featureStatusProposedCount && project.calculated?.featureStatusProposedCount > 0) {
            console.log("feature med")
            return "med"
        }

        console.log("feature low")
        return "low"
    }

    const getValuePriority = ():"high"|"med"|"low"|"notset" => {
        if(!project) {
            return "notset"
        }

        if(!project.projectValue || !project.projectValue.calculated?.netPresentValue || project.projectValue.calculated?.netPresentValue < 0.0) {
            return "high"
        }

        return "low"
    }

    const getMilestonePriority = ():"high"|"med"|"low"|"notset" => {
        if(!project) {
            return "notset"
        }

        if(project.calculated?.unhealthyTasks && project.calculated?.unhealthyTasks > 0) {
            return "high"
        }

        return "low"
    }

    onMount(() => {
        featurePriority = getFeaturePriority()
        valuePriority = getValuePriority()
        milestonePriority = getMilestonePriority()

        console.log("onmount", featurePriority)
    })
</script>


<div class="grid grid-cols-3 gap-16">
    <div>
        <BasicsSummary {project} />
    </div>

    <div class="col-span-2">
        <SectionSubHeading>TODO: Fill out the Details of this Project</SectionSubHeading>

        <TaskCard task="Break your project value down into a list of features" link="#features" priority={featurePriority}>
            This project currently has <b>{project.projectFeatures?.length}</b> {pluralize("feature", project.projectFeatures?.length as number)}

            {#if project.projectFeatures && project.projectFeatures?.length > 0}
            <ul>
                <li>{project.calculated?.featureStatusAcceptedCount} accepted</li>
                <li>{project.calculated?.featureStatusRemovedCount} removed</li>
                <li>{project.calculated?.featureStatusProposedCount} proposed</li>
                <li>{project.calculated?.featureStatusDoneCount} done</li>
            </ul>
            {/if}
        </TaskCard>

        <TaskCard task="Estimate and characterize the value generated by this project" link="#value" priority={valuePriority}>
            <div class="flex">
                <div class="pr-4">
                    This project has a 5-year NPV of 
                    <b>{formatCurrency.format(project.projectValue.calculated?.netPresentValue as number)} </b>
                    with an IRR of 
                    <b>{formatPercent.format(project.projectValue.calculated?.internalRateOfReturn as number)}</b>
                </div>
                {#if project.projectValue.projectValueLines && project.projectValue.projectValueLines.length > 0}
                <div>
                    <ProjectValueChart  {project} />
                </div>
                {/if}
            </div>
        </TaskCard>

        <TaskCard task="Create tasks and assign resources" link="#milestones" priority={milestonePriority}>
            This project currently has <b>{project.calculated?.totalTasks}</b> {pluralize("task", project.calculated?.totalTasks as number)}
            
            {#if project.calculated?.unhealthyTasks}
            <div class="text-yellow-400">
                Unhealthy tasks <b>{project.calculated?.unhealthyTasks}</b>
            </div>
            {:else}
            <div class="text-green-400">
                <b>{project.calculated?.healthyTasks}</b> tasks are healthy
            </div>
            {/if}
        </TaskCard>


        {#if showNextStatus}
        <div class="text-center mt-8">
        <UpdateStatusButtons {project} />
        <!-- 
			{#if canEnterStatus(project, "proposed")}
				<Button onclick={() => setStatus("proposed")} color="green" class="px-8 m-2 w-64">Propose this Project</Button>
			{:else}
				<Button disabled color="green" class="px-8 m-2 w-64">Propose this Project</Button>
			{/if}
		-->
        </div>
        {/if}
    </div>
</div>
