load('ext://helm_resource', 'helm_resource', 'helm_repo')
load('ext://namespace', 'namespace_create')

NAMESPACE = 'keycloak'

def setup_keycloak():
    namespace_create(NAMESPACE, allow_duplicates=True)

    helm_repo(
        'codecentric-repo', 
        'https://codecentric.github.io/helm-charts',
        labels=["HelmRepos"]
    )

    helm_resource(
        'keycloak', 
        'codecentric/keycloakx', 
        namespace = NAMESPACE, 
        flags=['--values=tilt_lib/keycloak/values.local.yaml'],
        labels=["Keycloak"],
        resource_deps=['postgres']
    )